schema = 3

[mod]
  [mod.'charm.land/fang/v2']
    version = 'v2.0.1'
    hash = 'sha256-gDGetHyMJIYiAWeUjgyESKwIZyE0HJTGcyrmZLE+h/E='

  [mod.'charm.land/lipgloss/v2']
    version = 'v2.0.4'
    hash = 'sha256-KrO8Q1/yQZBTMwysp/cAi5Kdz2/ZODBOr3C5X04zG/M='

  [mod.'github.com/alecthomas/chroma/v2']
    version = 'v2.20.0'
    hash = 'sha256-rL1mJS8fCltcii9w/efyyE4iyzogyjP+N80lE3CuzVE='

  [mod.'github.com/aymanbagabas/go-osc52/v2']
    version = 'v2.0.1'
    hash = 'sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg='

  [mod.'github.com/aymerick/douceur']
    version = 'v0.2.0'
    hash = 'sha256-NiBX8EfOvLXNiK3pJaZX4N73YgfzdrzRXdiBFe3X3sE='

  [mod.'github.com/charmbracelet/colorprofile']
    version = 'v0.4.3'
    hash = 'sha256-y+QDUxGOKhugEMQLRUTZYT2C+wKqYHnMLJ44jbh7+JA='

  [mod.'github.com/charmbracelet/lipgloss']
    version = 'v1.1.1-0.20250404203927-76690c660834'
    hash = 'sha256-CwS1AyoRsPOFA4SrC0CTtwLnbg57FmmSW/mvVQUFYcc='

  [mod.'github.com/charmbracelet/log']
    version = 'v1.0.0'
    hash = 'sha256-Veo9gqSs/ZHFNERzXSCtQjovaIwdr8YZkCIJ7xfTEGY='

  [mod.'github.com/charmbracelet/ultraviolet']
    version = 'v0.0.0-20260205113103-524a6607adb8'
    hash = 'sha256-zHe+nAS80nJPgZ4c3mU2HcHA9QL486b0BiyC4FNK3Nk='

  [mod.'github.com/charmbracelet/x/ansi']
    version = 'v0.11.7'
    hash = 'sha256-q8BZJq4K7NE5ETocN9/G/EoV0dUyD703ONSfHiUYzWQ='

  [mod.'github.com/charmbracelet/x/cellbuf']
    version = 'v0.0.15'
    hash = 'sha256-0S60XaWhKZG+TB3Kqe1oMn2Okwdq53nym8XayVSHHiM='

  [mod.'github.com/charmbracelet/x/exp/charmtone']
    version = 'v0.0.0-20250603201427-c31516f43444'
    hash = 'sha256-x6EfMobGGF31tnkjXuoGLxAa6V1ozsR2Z43TQu9/mX0='

  [mod.'github.com/charmbracelet/x/exp/slice']
    version = 'v0.0.0-20250327172914-2fdc97757edf'
    hash = 'sha256-C1tksnevc/RdytJRQg5LQ0+VVSWlTwbNGic649m6E1Q='

  [mod.'github.com/charmbracelet/x/mosaic']
    version = 'v0.0.0-20260705004817-2cc9a8fe1146'
    hash = 'sha256-PugVopmyhFhlVlugOzjdhHtH8aj98rnLk/nZn/EfTP8='

  [mod.'github.com/charmbracelet/x/term']
    version = 'v0.2.2'
    hash = 'sha256-KF7IU1Luxl/sZP6XjomWB2e3lxSUS4/5AahhapGir/4='

  [mod.'github.com/charmbracelet/x/termios']
    version = 'v0.1.1'
    hash = 'sha256-sri3LpHCBhGvnJldDzBxwbbZpeSGZVCJFOUL45uBFds='

  [mod.'github.com/charmbracelet/x/windows']
    version = 'v0.2.2'
    hash = 'sha256-CvmE8kAC5wlPSeWjl2hc5xizvGS2FeOLHw84froldkk='

  [mod.'github.com/clipperhouse/displaywidth']
    version = 'v0.11.0'
    hash = 'sha256-WokyTaofEy95xlshqK5YDzpemhXV5oaQifxS9YyfCXo='

  [mod.'github.com/clipperhouse/uax29/v2']
    version = 'v2.7.0'
    hash = 'sha256-GO3az7WiGcwU0OvmocwdfR5ohGRL8NbjscIaMyhAdxE='

  [mod.'github.com/dlclark/regexp2']
    version = 'v1.11.5'
    hash = 'sha256-jN5+2ED+YbIoPIuyJ4Ou5pqJb2w1uNKzp5yTjKY6rEQ='

  [mod.'github.com/go-logfmt/logfmt']
    version = 'v0.6.1'
    hash = 'sha256-+gUGmdR/QOsB9qKESLrsbq6tK2VssNT/kDbRFpgrZL4='

  [mod.'github.com/gorilla/css']
    version = 'v1.0.1'
    hash = 'sha256-6JwNHqlY2NpZ0pSQTyYPSpiNqjXOdFHqrUT10sv3y8A='

  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/iwnuplynottyan/glamoured']
    version = 'v0.0.0-20260719193130-e37922939119'
    hash = 'sha256-m6EtXilcOIIgG2QxX0YBv5Z+u9KR+wTppRlldXyPLhc='

  [mod.'github.com/lucasb-eyer/go-colorful']
    version = 'v1.4.0'
    hash = 'sha256-i/3GDHKEMLCy0kc3mtyk58UWYOPmKoUVaq6QCAWXKP0='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.20'
    hash = 'sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ='

  [mod.'github.com/mattn/go-runewidth']
    version = 'v0.0.23'
    hash = 'sha256-SmChZ2U1aR8pW3LPhdM7KcVF5TO6VcHgRzBtUXbBWJA='

  [mod.'github.com/microcosm-cc/bluemonday']
    version = 'v1.0.27'
    hash = 'sha256-EZSya9FLPQ83CL7N2cZy21fdS35hViTkiMK5f3op8Es='

  [mod.'github.com/muesli/cancelreader']
    version = 'v0.2.2'
    hash = 'sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ='

  [mod.'github.com/muesli/mango']
    version = 'v0.1.0'
    hash = 'sha256-Xy63UxeZJMU4JlG6uuEpUeyxTGytx+NDbqCAgXpZrrU='

  [mod.'github.com/muesli/mango-cobra']
    version = 'v1.2.0'
    hash = 'sha256-26X9H9t2Z/kLII2n/Zd+D568H2rlbVJPS11jT25bdUA='

  [mod.'github.com/muesli/mango-pflag']
    version = 'v0.1.0'
    hash = 'sha256-qgUxVjVFmbcGjn8m58DRRu4hmYhirEUDy9TjkJYU8m4='

  [mod.'github.com/muesli/roff']
    version = 'v0.1.0'
    hash = 'sha256-0A/M8h0+dSF1NruiGjs4WbfWENFbV3VpyIwJzHEeRlA='

  [mod.'github.com/muesli/termenv']
    version = 'v0.16.0'
    hash = 'sha256-hGo275DJlyLtcifSLpWnk8jardOksdeX9lH4lBeE3gI='

  [mod.'github.com/rivo/uniseg']
    version = 'v0.4.7'
    hash = 'sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo='

  [mod.'github.com/spf13/cobra']
    version = 'v1.10.2'
    hash = 'sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.9'
    hash = 'sha256-YAjyYpq5BXCosVJtvYLWFG1t4gma2ylzc7ILLoj/hD8='

  [mod.'github.com/xo/terminfo']
    version = 'v0.0.0-20220910002029-abceb7e1c41e'
    hash = 'sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU='

  [mod.'github.com/yuin/goldmark']
    version = 'v1.7.17'
    hash = 'sha256-QC6s1ai8rS/oOn/U9lQQEDTNUExdpn+diKPNdUi7k74='

  [mod.'github.com/yuin/goldmark-emoji']
    version = 'v1.0.6'
    hash = 'sha256-+d6bZzOPE+JSFsZbQNZMCWE+n3jgcQnkPETVk47mxSY='

  [mod.'golang.org/x/exp']
    version = 'v0.0.0-20231006140011-7918f672742d'
    hash = 'sha256-2SO1etTQ6UCUhADR5sgvDEDLHcj77pJKCIa/8mGDbAo='

  [mod.'golang.org/x/image']
    version = 'v0.43.0'
    hash = 'sha256-GKd2YyREOkKGh4xfpgOo9eOc1gzzMRXrIEH1SmJ2688='

  [mod.'golang.org/x/net']
    version = 'v0.57.0'
    hash = 'sha256-gKo8UMw4hfETBHm8N5GOfuNadse9TWEQXJo2YWq5bY4='

  [mod.'golang.org/x/sync']
    version = 'v0.22.0'
    hash = 'sha256-VZjl0fAM0p/nI81zh+pdBjzxFupx0UcKYXBBpL2ZS7k='

  [mod.'golang.org/x/sys']
    version = 'v0.47.0'
    hash = 'sha256-TpbRyWWqHjddP6QzUgAbaLd2EE0S+GYNRUIDJd18r98='

  [mod.'golang.org/x/text']
    version = 'v0.40.0'
    hash = 'sha256-LJfnki46XEreGbSgjl+DeqgcTsINTOu2owyXNvijMcA='
