name: nixHash

on:
  push:
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'gomod2nix.toml'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Update gomod2nix.toml
        run: nix run github:nix-community/gomod2nix -- generate

      - name: Get correct vendorHash
        run: |
          CORRECT=$(nix build .# 2>&1 | grep "got:" | awk '{print $2}')
          echo "Correct hash: $CORRECT"
          
          sed -i "s|vendorHash = .*|vendorHash = \"$CORRECT\";|" flake.nix

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update vendorHash"
