steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Update gomod2nix.toml
        run: nix run github:nix-community/gomod2nix -- generate

      - name: Get correct vendorHash
        run: |
          CORRECT=$(nix build .# 2>&1 | grep "got:" | awk '{print $2}')
          echo "Correct hash: $CORRECT"
          
          if [ -n "$CORRECT" ]; then
            sed -i "s|vendorHash = .*|vendorHash = \"$CORRECT\";|" flake.nix
          else
            echo "No vendorHash mismatch found or build failed."
          fi

      - name: Pull latest changes
        run: git pull origin ${{ github.ref_name }} --rebase

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update vendorHash"
